#ifndef MATHS_TOPOLOGY_TOPOLOGICAL_SPACES_HPP
#define MATHS_TOPOLOGY_TOPOLOGICAL_SPACES_HPP

#include <vector>
#include <set>
#include <functional>
#include <algorithm>
#include <string>
#include <stdexcept>

/**
 * @file topological_spaces.hpp
 * @brief Topological spaces, weak topologies, and semicontinuity
 *
 * Implements:
 * - General topological spaces
 * - Weak topologies
 * - Separation axioms (T0, T1, T2/Hausdorff, etc.)
 * - Semicontinuous functions
 * - Baire spaces
 */

namespace maths::topology {

/**
 * @class TopologicalSpaceProperties
 * @brief Properties and theorems about topological spaces
 */
class TopologicalSpaceProperties {
public:
    /**
     * @brief Definition of topological space
     */
    static std::string definition() {
        return "Topological Space:\n"
               "\n"
               "A topological space is a pair (X, τ) where X is a set\n"
               "and τ is a collection of subsets of X (called open sets) satisfying:\n"
               "\n"
               "1. ∅, X ∈ τ\n"
               "2. Arbitrary unions of sets in τ are in τ\n"
               "3. Finite intersections of sets in τ are in τ\n"
               "\n"
               "The collection τ is called a topology on X.\n"
               "\n"
               "Examples:\n"
               "- Discrete topology: τ = P(X) (all subsets)\n"
               "- Indiscrete/trivial topology: τ = {∅, X}\n"
               "- Metric topology: τ generated by open balls";
    }

    /**
     * @brief Separation axioms
     */
    static std::string separationAxioms() {
        return "Separation Axioms:\n"
               "\n"
               "T₀ (Kolmogorov): For distinct x, y, ∃ open set\n"
               "  containing one but not the other\n"
               "\n"
               "T₁ (Fréchet): For distinct x, y, ∃ open sets U, V\n"
               "  with x ∈ U, y ∉ U and y ∈ V, x ∉ V\n"
               "  Equivalently: singletons {x} are closed\n"
               "\n"
               "T₂ (Hausdorff): For distinct x, y, ∃ disjoint open sets\n"
               "  U, V with x ∈ U, y ∈ V\n"
               "  (can separate points by open neighborhoods)\n"
               "\n"
               "T₃ (Regular): T₀ + for closed F and x ∉ F,\n"
               "  ∃ disjoint open sets separating x and F\n"
               "\n"
               "T₃½ (Tychonoff/Completely regular): T₀ + for closed F\n"
               "  and x ∉ F, ∃ continuous f: X → [0,1]\n"
               "  with f(x) = 0, f(F) = {1}\n"
               "\n"
               "T₄ (Normal): T₁ + for disjoint closed F, G,\n"
               "  ∃ disjoint open sets separating F and G\n"
               "\n"
               "Hierarchy: T₄ ⇒ T₃½ ⇒ T₃ ⇒ T₂ ⇒ T₁ ⇒ T₀\n"
               "\n"
               "Note: All metric spaces are T₄ (normal).";
    }

    /**
     * @brief Connectedness
     */
    static std::string connectedness() {
        return "Connectedness:\n"
               "\n"
               "X is connected if it cannot be written as X = U ∪ V\n"
               "where U, V are non-empty, disjoint, and open.\n"
               "\n"
               "Equivalent definitions:\n"
               "1. No non-trivial clopen sets (sets both open and closed)\n"
               "2. Every continuous f: X → {0,1} is constant\n"
               "\n"
               "Path-connected: ∀x, y ∈ X, ∃ continuous path γ: [0,1] → X\n"
               "  with γ(0) = x, γ(1) = y\n"
               "\n"
               "Theorem: Path-connected ⇒ Connected\n"
               "(converse false: topologist's sine curve)\n"
               "\n"
               "Intermediate Value Theorem: If f: X → ℝ continuous\n"
               "and X connected, then f(X) is an interval.";
    }

    /**
     * @brief Bases and subbases
     */
    static std::string basesSubbases() {
        return "Bases and Subbases:\n"
               "\n"
               "Base: Collection 𝓑 of open sets such that every open set\n"
               "  is a union of sets from 𝓑\n"
               "\n"
               "Conditions for 𝓑 to be a base:\n"
               "1. ⋃𝓑 = X (cover X)\n"
               "2. For B₁, B₂ ∈ 𝓑 and x ∈ B₁ ∩ B₂,\n"
               "   ∃B₃ ∈ 𝓑: x ∈ B₃ ⊆ B₁ ∩ B₂\n"
               "\n"
               "Example: Open balls form base for metric topology\n"
               "\n"
               "Subbase: Collection 𝓢 such that finite intersections\n"
               "  of sets from 𝓢 form a base\n"
               "\n"
               "Any collection 𝓢 can be made into a subbase by declaring\n"
               "it generates the coarsest topology containing 𝓢.";
    }
};

/**
 * @class WeakTopology
 * @brief Weak topologies and weak* topologies
 */
class WeakTopology {
public:
    /**
     * @brief Initial topology / weak topology
     */
    static std::string initialTopology() {
        return "Initial/Weak Topology:\n"
               "\n"
               "Given: X set, {(Yᵢ, τᵢ)}ᵢ∈I topological spaces,\n"
               "       functions fᵢ: X → Yᵢ\n"
               "\n"
               "The initial topology on X (induced by {fᵢ}) is the\n"
               "coarsest topology making all fᵢ continuous.\n"
               "\n"
               "Subbase: {fᵢ⁻¹(U) : i ∈ I, U open in Yᵢ}\n"
               "\n"
               "Universal property: g: Z → X continuous ⟺\n"
               "  fᵢ ∘ g: Z → Yᵢ continuous for all i\n"
               "\n"
               "Examples:\n"
               "- Subspace topology: Y ⊆ X, f: Y → X inclusion\n"
               "- Product topology: X = ∏Xᵢ, πᵢ: X → Xᵢ projections\n"
               "- Weak topology on normed space: induced by\n"
               "  continuous linear functionals";
    }

    /**
     * @brief Final topology / quotient topology
     */
    static std::string finalTopology() {
        return "Final/Quotient Topology:\n"
               "\n"
               "Given: X set, {(Yᵢ, τᵢ)}ᵢ∈I topological spaces,\n"
               "       functions fᵢ: Yᵢ → X\n"
               "\n"
               "The final topology on X is the finest topology\n"
               "making all fᵢ continuous.\n"
               "\n"
               "U ⊆ X open ⟺ fᵢ⁻¹(U) open in Yᵢ for all i\n"
               "\n"
               "Universal property: g: X → Z continuous ⟺\n"
               "  g ∘ fᵢ: Yᵢ → Z continuous for all i\n"
               "\n"
               "Examples:\n"
               "- Quotient topology: X/~ with π: X → X/~\n"
               "- Coproduct (disjoint union) topology";
    }

    /**
     * @brief Weak topology on Banach spaces
     */
    static std::string weakTopologyBanach() {
        return "Weak Topology on Banach Spaces:\n"
               "\n"
               "For Banach space X with dual X*, the weak topology σ(X, X*)\n"
               "is the coarsest topology making all f ∈ X* continuous.\n"
               "\n"
               "Subbase: {f⁻¹(U) : f ∈ X*, U open in ℝ}\n"
               "\n"
               "Convergence: xₙ ⇀ x (weak) ⟺ f(xₙ) → f(x) ∀f ∈ X*\n"
               "\n"
               "Properties:\n"
               "- Weaker than norm topology (fewer open sets)\n"
               "- Bounded sets in weak topology = bounded in norm\n"
               "- Closed convex sets: weak closure = norm closure\n"
               "- Sequential compactness: reflexive spaces have\n"
               "  bounded sequences with weakly convergent subsequences\n"
               "\n"
               "Weak* topology σ(X*, X) on X*:\n"
               "- Induced by evaluation maps φₓ: X* → ℝ, f ↦ f(x)\n"
               "- fₙ ⇀* f ⟺ fₙ(x) → f(x) ∀x ∈ X\n"
               "- Banach-Alaoglu: Closed unit ball in X* is\n"
               "  weak* compact";
    }
};

/**
 * @class Semicontinuity
 * @brief Lower and upper semicontinuous functions
 */
class Semicontinuity {
public:
    /**
     * @brief Lower semicontinuity
     */
    static std::string lowerSemicontinuous() {
        return "Lower Semicontinuous Functions:\n"
               "\n"
               "f: X → ℝ ∪ {+∞} is lower semicontinuous (lsc) at x₀ if:\n"
               "  lim inf_{x→x₀} f(x) ≥ f(x₀)\n"
               "\n"
               "Equivalently:\n"
               "1. ∀α ∈ ℝ, {x : f(x) > α} is open (sublevel sets open)\n"
               "2. ∀xₙ → x₀, lim inf f(xₙ) ≥ f(x₀)\n"
               "3. epigraph epi(f) = {(x,t) : f(x) ≤ t} is closed\n"
               "\n"
               "Properties:\n"
               "- Supremum of lsc functions is lsc\n"
               "- Sum of lsc functions is lsc (if defined)\n"
               "- lsc function on compact set attains minimum\n"
               "\n"
               "Example: indicator function I_C(x) = 0 if x ∈ C,\n"
               "  +∞ otherwise, is lsc ⟺ C is closed";
    }

    /**
     * @brief Upper semicontinuity
     */
    static std::string upperSemicontinuous() {
        return "Upper Semicontinuous Functions:\n"
               "\n"
               "f: X → ℝ ∪ {-∞} is upper semicontinuous (usc) at x₀ if:\n"
               "  lim sup_{x→x₀} f(x) ≤ f(x₀)\n"
               "\n"
               "Equivalently:\n"
               "1. ∀α ∈ ℝ, {x : f(x) < α} is open\n"
               "2. -f is lower semicontinuous\n"
               "3. hypograph hypo(f) = {(x,t) : f(x) ≥ t} is closed\n"
               "\n"
               "Properties:\n"
               "- Infimum of usc functions is usc\n"
               "- usc function on compact set attains maximum\n"
               "\n"
               "Theorem: f continuous ⟺ f both lsc and usc\n"
               "\n"
               "Application (Weierstrass Theorem): Continuous function\n"
               "on non-empty compact set attains max and min.";
    }

    /**
     * @brief Existence theorems via semicontinuity
     */
    static std::string existenceResults() {
        return "Existence Results via Semicontinuity:\n"
               "\n"
               "Theorem 1 (Minimum): If f: X → ℝ ∪ {+∞} is lsc\n"
               "and K ⊆ X is non-empty, compact, then:\n"
               "  inf_{x ∈ K} f(x) is attained (if finite)\n"
               "\n"
               "Theorem 2 (Maximum): If f: X → ℝ ∪ {-∞} is usc\n"
               "and K ⊆ X is non-empty, compact, then:\n"
               "  sup_{x ∈ K} f(x) is attained (if finite)\n"
               "\n"
               "Corollary (Weierstrass): Continuous function on\n"
               "non-empty compact set attains its bounds.\n"
               "\n"
               "Application: Many optimization problems can be solved\n"
               "by showing objective is lsc and constraint set is compact.\n"
               "\n"
               "Relaxation: If minimization problem has no solution,\n"
               "replace f with lsc envelope (largest lsc function ≤ f).";
    }
};

/**
 * @class BaireSpaces
 * @brief Baire category theorem and applications
 */
class BaireSpaces {
public:
    /**
     * @brief Baire Category Theorem
     */
    static std::string categoryTheorem() {
        return "Baire Category Theorem:\n"
               "\n"
               "In a complete metric space (or locally compact Hausdorff),\n"
               "the intersection of countably many dense open sets is dense.\n"
               "\n"
               "Equivalently: Complete metric space cannot be written\n"
               "as countable union of nowhere dense sets.\n"
               "\n"
               "Definitions:\n"
               "- Dense: cl(A) = X\n"
               "- Nowhere dense: int(cl(A)) = ∅\n"
               "- Meager (first category): countable union of nowhere dense\n"
               "- Comeager/residual (second category): complement is meager\n"
               "\n"
               "Baire space: non-empty open set is not meager\n"
               "(equivalently: BCT holds)\n"
               "\n"
               "Examples: ℝⁿ, C[0,1], Lᵖ spaces are Baire.";
    }

    /**
     * @brief Uniform Boundedness Theorem
     */
    static std::string uniformBoundedness() {
        return "Uniform Boundedness Theorem (Banach-Steinhaus):\n"
               "\n"
               "Let X be Banach space, Y normed space,\n"
               "and {Tᵢ}ᵢ∈I family of continuous linear operators Tᵢ: X → Y.\n"
               "\n"
               "If ∀x ∈ X, sup_{i∈I} ‖Tᵢ(x)‖ < ∞ (pointwise bounded),\n"
               "then sup_{i∈I} ‖Tᵢ‖ < ∞ (uniformly bounded).\n"
               "\n"
               "Proof uses Baire Category Theorem!\n"
               "\n"
               "Consequences:\n"
               "1. If Tₙ(x) converges for all x, then {‖Tₙ‖} is bounded\n"
               "\n"
               "2. There exists continuous function f with Fourier series\n"
               "   diverging at a point\n"
               "\n"
               "3. Strong convergence of {Tₙ} (operator norm) is stronger\n"
               "   than weak convergence (pointwise)";
    }

    /**
     * @brief Open Mapping Theorem
     */
    static std::string openMappingTheorem() {
        return "Open Mapping Theorem (Banach-Schauder):\n"
               "\n"
               "If T: X → Y is surjective continuous linear operator\n"
               "between Banach spaces, then T is an open mapping\n"
               "(maps open sets to open sets).\n"
               "\n"
               "Consequences:\n"
               "\n"
               "1. Inverse Mapping Theorem: If T: X → Y bijective\n"
               "   continuous linear between Banach spaces,\n"
               "   then T⁻¹ is continuous (i.e., T is homeomorphism)\n"
               "\n"
               "2. Closed Graph Theorem: T: X → Y linear between\n"
               "   Banach spaces is continuous ⟺ graph is closed\n"
               "\n"
               "All three theorems (UBT, OMT, CGT) are equivalent\n"
               "and rely on Baire Category Theorem.\n"
               "\n"
               "Application: Two norms ‖·‖₁, ‖·‖₂ on Banach space\n"
               "are equivalent ⟺ they induce same topology.";
    }
};

} // namespace maths::topology

#endif // MATHS_TOPOLOGY_TOPOLOGICAL_SPACES_HPP
